version: '3'

services:
  app1:
    build:
      context: ./
        dockerfile: Dockerfile-ci
    ports:
      - 3100:3100
    command: bin/entrypoint.sh
    env_file:
      - .env.docker-compose
    environment:
      - NODE_ENV=development
      - APP_PORT=3100
      - RPCUSER=test
      - RPCPASSWORD=test
      - RPCHOSTNAME=feature1.particl.xyz
      - MAINNET_PORT=52738
      - TESTNET_PORT=52935

  app2:
    build:
      context: ./
        dockerfile: Dockerfile-ci
    ports:
      - 3200:3200
    command: bin/entrypoint.sh
    env_file:
      - .env.docker-compose
    environment:
      - NODE_ENV=development
      - APP_PORT=3200
      - RPCUSER=test
      - RPCPASSWORD=test
      - RPCHOSTNAME=feature2.particl.xyz
      - MAINNET_PORT=53738
      - TESTNET_PORT=53935

