version: '2'

networks:
    internal:
        driver: bridge

services:
  app1:
#    build:
#      context: ./
#      dockerfile: Dockerfile.ci
    image: r.cfcr.io/ludx/dapp-shell-ci:feature
#    volumes:
#      - .:/app/
#      - ./data/app1:/app/data
#      - ./data/app1_node_modules:/app/node_modules
    expose:
      - 3100
    ports:
      - 3100:3100
    networks:
      - internal
    privileged: true

    command: bin/ci-entrypoint.sh
    env_file:
      - .env.docker-compose
    environment:
      - NODE_ENV=development
      - APP_PORT=3100
      - APP_HOST=http://localhost
      - RPCUSER=test
      - RPCPASSWORD=test
      - RPCHOSTNAME=feature1.particl.xyz
      - MAINNET_PORT=52738
      - TESTNET_PORT=52935
    networks:
        - internal
    privileged: true

  app2:
#    build:
#      context: ./
#      dockerfile: Dockerfile.ci
    image: r.cfcr.io/ludx/dapp-shell-ci:feature
#    volumes:
#      - .:/app/
#      - ./data/app2:/app/data
#      - ./data/app2_node_modules:/app/node_modules
    expose:
      - 3200
    ports:
      - 3200:3200
    command: bin/ci-entrypoint.sh
    networks:
      - internal
    privileged: true

    env_file:
      - .env.docker-compose
    environment:
      - NODE_ENV=development
      - APP_PORT=3200
      - RPCUSER=test
      - RPCPASSWORD=test
      - RPCHOSTNAME=feature2.particl.xyz
      - MAINNET_PORT=53738
      - TESTNET_PORT=53935
