---
stack: ludx/dappshelldev-stack
version: 0.1.0
services:

  particld1:
    image: ludx/particl:latest
    instances: 1
    volumes:
      - /root/data/particld-dev1:/root/.particl
    environment:
      - CONF_TESTNET=1                  # Use the test chain
      - CONF_RPCUSERNAME=test           # Username for JSON-RPC connections, generated unless set
      - CONF_RPCPASSWORD=test           # Password for JSON-RPC connections, generated unless set
      - CONF_PRINTTOCONSOLE=0           # Send trace/debug info to console instead of debug.log file
      - CONF_SERVER=1                   # Accept command line and JSON-RPC commands
      - CONF_RPCALLOWIP=0.0.0.0/0       # Allow JSON-RPC connections from specified source. Valid for <ip> are a single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0) or a network/CIDR (e.g. 1.2.3.4/24).
      - CONF_LISTEN=1                   # Accept connections from outside (default: 1 if no -proxy or -connect)
#      - CREATEDEFAULTMASTERKEY=true
    ports:
      - 52738:51738
      - 52935:51935
    affinity:
      - node==kontena-agent1
#      - label==devenv=1

  particld2:
    image: ludx/particl:latest
    instances: 1
    volumes:
      - /root/data/particld-dev2:/root/.particl
    environment:
      - CONF_TESTNET=1                  # Use the test chain
      - CONF_RPCUSERNAME=test           # Username for JSON-RPC connections, generated unless set
      - CONF_RPCPASSWORD=test           # Password for JSON-RPC connections, generated unless set
      - CONF_PRINTTOCONSOLE=0           # Send trace/debug info to console instead of debug.log file
      - CONF_SERVER=1                   # Accept command line and JSON-RPC commands
      - CONF_RPCALLOWIP=0.0.0.0/0       # Allow JSON-RPC connections from specified source. Valid for <ip> are a single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0) or a network/CIDR (e.g. 1.2.3.4/24).
      - CONF_LISTEN=1                   # Accept connections from outside (default: 1 if no -proxy or -connect)
#      - CREATEDEFAULTMASTERKEY=true
    ports:
      - 53738:51738
      - 53935:51935
    affinity:
      - node==kontena-agent1
#      - label==devenv=1

  particld3:
    image: ludx/particl:latest
    instances: 1
    volumes:
      - /root/data/particld-dev3:/root/.particl
    environment:
      - CONF_TESTNET=1                  # Use the test chain
      - CONF_RPCUSERNAME=test           # Username for JSON-RPC connections, generated unless set
      - CONF_RPCPASSWORD=test           # Password for JSON-RPC connections, generated unless set
      - CONF_PRINTTOCONSOLE=0           # Send trace/debug info to console instead of debug.log file
      - CONF_SERVER=1                   # Accept command line and JSON-RPC commands
      - CONF_RPCALLOWIP=0.0.0.0/0       # Allow JSON-RPC connections from specified source. Valid for <ip> are a single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0) or a network/CIDR (e.g. 1.2.3.4/24).
      - CONF_LISTEN=1                   # Accept connections from outside (default: 1 if no -proxy or -connect)
#      - CREATEDEFAULTMASTERKEY=true
    ports:
      - 54738:51738
      - 54935:51935
    affinity:
      - node==kontena-agent1
#      - label==devenv=1

  dapp-shell-ci:
    image: r.cfcr.io/ludx/dapp-shell-ci:latest
    depends_on:
      - particld3
    links:
      - particld3
      - loadbalancerstack/internet_lb
    volumes:
      - /root/data/dapp-shell-ci:/app/data
    environment:
      - NODE_ENV=development
      - APP_NAME=dapp-shell
      - APP_HOST=http://dev.particl.xyz
      - APP_URL_PREFIX=/api
      - APP_PORT=3333
      - RPCUSER=test
      - RPCPASSWORD=test
      - RPCHOSTNAME=particld3
      - MAINNET_PORT=51738
      - TESTNET_PORT=51935
      - LOG_LEVEL=debug
      - LOG_ADAPTER=winston
      - API_INFO_ENABLED=true
      - API_INFO_ROUTE=/info
      - CLI_ENABLED=true
      - CLI_ROUTE=/cli
      - SWAGGER_ENABLED=true
      - SWAGGER_ROUTE=/docs
      - SWAGGER_FILE=/app/src/api/swagger.json
      - MONITOR_ENABLED=true
      - MONITOR_ROUTE=/status
      - DB_CLIENT=sqlite3
      - DB_CONNECTION=/app/data/marketplace.db
      - DB_POOL_MIN=2
      - DB_POOL_MAX=10
      - DB_MIGRATION_DIR=/app/src/database/migrations
      - DB_MIGRATION_TABLE=version
      - DB_SEEDS_DIR=/app/src/database/seeds
      - KONTENA_LB_MODE=http
      - KONTENA_LB_BALANCE=roundrobin
      - KONTENA_LB_INTERNAL_PORT=3333
      - KONTENA_LB_VIRTUAL_HOSTS=dev.particl.xyz
#    ports:
#      - 3333:3333
    affinity:
      - node==kontena-agent1
#      - label==devenv=1
